---
- name: Get VPC facts
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ vpc_tag | upper }}"
  register: vpc_net_facts
...
