---
- name: Get VPC Information
  include_tasks: "get_vpc_facts.yml"
  vars:
    vpc_tag: "{{ aws_vpc.aws_vpc_name }}"

- name: Delete Virtual Private Cloud {{ aws_vpc.aws_vpc_name }}
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ aws_vpc.aws_vpc_region }}"
    name: "{{ aws_vpc.aws_vpc_name }}"
    cidr_block: "{{ aws_vpc.aws_vpc_cidr_main }}"
    state: "absent"
...
